### ISSUE TITLE
Fix regression with Aevilia GB

### ISSUE THREAD

**Issue by ParzivalWolfram** [ParzivalWolfram/GameYob-Accurate#2]
GameYob-Accurate has a regression causing [Aevilia GB](https://github.com/ISSOtm/Aevilia-GB) to claim the emulator is trying to bypass the anti-DMG lockout via spoofing. Cause unknown as of now.

**Comment by ISSOtm** [comment]
Requirements to trigger the spoof screen:
- Emulate Echo RAM
- Emulate the GBC-only undocumented register $FF6C
- Not set WRAM bank 1 at start-up (this is normally the case, although SVBK reads $E8, which would translate to bank 0, but the hardware hard-wires 0 to bank 1)

**Comment by ParzivalWolfram** [comment]
Thanks, man.

**Comment by ParzivalWolfram** [comment]
Found the issue: I'm only forcing WRAM bank 0 to be WRAM bank 1 on invalid bank request. Whoops.

**Comment by ParzivalWolfram** [comment]
@ISSOtm all 3 are emulated properly, however the spoof screen persists.

**Comment by ParzivalWolfram** [comment]
It might help if I was checking for invalid WRAM bankswitches and not invalid SRAM bankswitches. I'm a dumbass. Should be fixed now. Also, FF6C was readable on both DMG and CGB.

I should stop coding at 3 AM.
